pipeline {
    agent any

    tools {
        maven "mavenTool"
        jdk "jdk8"
    }

    stages {
        
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
     }
    
}
